// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.7.1
// source: egida.proto

package grpc

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Service struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *Service) Reset() {
	*x = Service{}
	if protoimpl.UnsafeEnabled {
		mi := &file_egida_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_egida_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_egida_proto_rawDescGZIP(), []int{0}
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListService struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Services []*Service `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
}

func (x *ListService) Reset() {
	*x = ListService{}
	if protoimpl.UnsafeEnabled {
		mi := &file_egida_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListService) ProtoMessage() {}

func (x *ListService) ProtoReflect() protoreflect.Message {
	mi := &file_egida_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListService.ProtoReflect.Descriptor instead.
func (*ListService) Descriptor() ([]byte, []int) {
	return file_egida_proto_rawDescGZIP(), []int{1}
}

func (x *ListService) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

type ServiceNameReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ServiceNameReq) Reset() {
	*x = ServiceNameReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_egida_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceNameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceNameReq) ProtoMessage() {}

func (x *ServiceNameReq) ProtoReflect() protoreflect.Message {
	mi := &file_egida_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceNameReq.ProtoReflect.Descriptor instead.
func (*ServiceNameReq) Descriptor() ([]byte, []int) {
	return file_egida_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceNameReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListServicesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListServicesReq) Reset() {
	*x = ListServicesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_egida_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListServicesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesReq) ProtoMessage() {}

func (x *ListServicesReq) ProtoReflect() protoreflect.Message {
	mi := &file_egida_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesReq.ProtoReflect.Descriptor instead.
func (*ListServicesReq) Descriptor() ([]byte, []int) {
	return file_egida_proto_rawDescGZIP(), []int{3}
}

type Package struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Package) Reset() {
	*x = Package{}
	if protoimpl.UnsafeEnabled {
		mi := &file_egida_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Package) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Package) ProtoMessage() {}

func (x *Package) ProtoReflect() protoreflect.Message {
	mi := &file_egida_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Package.ProtoReflect.Descriptor instead.
func (*Package) Descriptor() ([]byte, []int) {
	return file_egida_proto_rawDescGZIP(), []int{4}
}

func (x *Package) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListPackage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Packages []*Package `protobuf:"bytes,1,rep,name=packages,proto3" json:"packages,omitempty"`
}

func (x *ListPackage) Reset() {
	*x = ListPackage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_egida_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPackage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPackage) ProtoMessage() {}

func (x *ListPackage) ProtoReflect() protoreflect.Message {
	mi := &file_egida_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPackage.ProtoReflect.Descriptor instead.
func (*ListPackage) Descriptor() ([]byte, []int) {
	return file_egida_proto_rawDescGZIP(), []int{5}
}

func (x *ListPackage) GetPackages() []*Package {
	if x != nil {
		return x.Packages
	}
	return nil
}

type ListPackagesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListPackagesReq) Reset() {
	*x = ListPackagesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_egida_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPackagesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPackagesReq) ProtoMessage() {}

func (x *ListPackagesReq) ProtoReflect() protoreflect.Message {
	mi := &file_egida_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPackagesReq.ProtoReflect.Descriptor instead.
func (*ListPackagesReq) Descriptor() ([]byte, []int) {
	return file_egida_proto_rawDescGZIP(), []int{6}
}

type LynisScore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Score string   `protobuf:"bytes,1,opt,name=score,proto3" json:"score,omitempty"`
	Log   []string `protobuf:"bytes,2,rep,name=log,proto3" json:"log,omitempty"`
}

func (x *LynisScore) Reset() {
	*x = LynisScore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_egida_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LynisScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LynisScore) ProtoMessage() {}

func (x *LynisScore) ProtoReflect() protoreflect.Message {
	mi := &file_egida_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LynisScore.ProtoReflect.Descriptor instead.
func (*LynisScore) Descriptor() ([]byte, []int) {
	return file_egida_proto_rawDescGZIP(), []int{7}
}

func (x *LynisScore) GetScore() string {
	if x != nil {
		return x.Score
	}
	return ""
}

func (x *LynisScore) GetLog() []string {
	if x != nil {
		return x.Log
	}
	return nil
}

type ScoreReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ScoreReq) Reset() {
	*x = ScoreReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_egida_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScoreReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreReq) ProtoMessage() {}

func (x *ScoreReq) ProtoReflect() protoreflect.Message {
	mi := &file_egida_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreReq.ProtoReflect.Descriptor instead.
func (*ScoreReq) Descriptor() ([]byte, []int) {
	return file_egida_proto_rawDescGZIP(), []int{8}
}

type Port struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int64 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *Port) Reset() {
	*x = Port{}
	if protoimpl.UnsafeEnabled {
		mi := &file_egida_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Port) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Port) ProtoMessage() {}

func (x *Port) ProtoReflect() protoreflect.Message {
	mi := &file_egida_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Port.ProtoReflect.Descriptor instead.
func (*Port) Descriptor() ([]byte, []int) {
	return file_egida_proto_rawDescGZIP(), []int{9}
}

func (x *Port) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

type ListPort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ports []*Port `protobuf:"bytes,1,rep,name=ports,proto3" json:"ports,omitempty"`
}

func (x *ListPort) Reset() {
	*x = ListPort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_egida_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPort) ProtoMessage() {}

func (x *ListPort) ProtoReflect() protoreflect.Message {
	mi := &file_egida_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPort.ProtoReflect.Descriptor instead.
func (*ListPort) Descriptor() ([]byte, []int) {
	return file_egida_proto_rawDescGZIP(), []int{10}
}

func (x *ListPort) GetPorts() []*Port {
	if x != nil {
		return x.Ports
	}
	return nil
}

type HasGUI struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gui bool `protobuf:"varint,1,opt,name=gui,proto3" json:"gui,omitempty"`
}

func (x *HasGUI) Reset() {
	*x = HasGUI{}
	if protoimpl.UnsafeEnabled {
		mi := &file_egida_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HasGUI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasGUI) ProtoMessage() {}

func (x *HasGUI) ProtoReflect() protoreflect.Message {
	mi := &file_egida_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasGUI.ProtoReflect.Descriptor instead.
func (*HasGUI) Descriptor() ([]byte, []int) {
	return file_egida_proto_rawDescGZIP(), []int{11}
}

func (x *HasGUI) GetGui() bool {
	if x != nil {
		return x.Gui
	}
	return false
}

type HasGUIReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HasGUIReq) Reset() {
	*x = HasGUIReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_egida_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HasGUIReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasGUIReq) ProtoMessage() {}

func (x *HasGUIReq) ProtoReflect() protoreflect.Message {
	mi := &file_egida_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasGUIReq.ProtoReflect.Descriptor instead.
func (*HasGUIReq) Descriptor() ([]byte, []int) {
	return file_egida_proto_rawDescGZIP(), []int{12}
}

type ListOpenPortsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListOpenPortsReq) Reset() {
	*x = ListOpenPortsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_egida_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOpenPortsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOpenPortsReq) ProtoMessage() {}

func (x *ListOpenPortsReq) ProtoReflect() protoreflect.Message {
	mi := &file_egida_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOpenPortsReq.ProtoReflect.Descriptor instead.
func (*ListOpenPortsReq) Descriptor() ([]byte, []int) {
	return file_egida_proto_rawDescGZIP(), []int{13}
}

var File_egida_proto protoreflect.FileDescriptor

var file_egida_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x65, 0x67, 0x69, 0x64, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67,
	0x72, 0x70, 0x63, 0x22, 0x35, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x38, 0x0a, 0x0b, 0x4c, 0x69,
	0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x29, 0x0a, 0x08, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x22, 0x24, 0x0a, 0x0e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x11, 0x0a, 0x0f, 0x4c, 0x69,
	0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x22, 0x1d, 0x0a,
	0x07, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x38, 0x0a, 0x0b,
	0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x12, 0x29, 0x0a, 0x08, 0x70,
	0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x52, 0x08, 0x70, 0x61,
	0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x22, 0x11, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x61,
	0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x71, 0x22, 0x34, 0x0a, 0x0a, 0x4c, 0x79, 0x6e,
	0x69, 0x73, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x6c, 0x6f, 0x67, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x6f, 0x67, 0x22,
	0x0a, 0x0a, 0x08, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x22, 0x1e, 0x0a, 0x04, 0x50,
	0x6f, 0x72, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x2c, 0x0a, 0x08, 0x4c,
	0x69, 0x73, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x20, 0x0a, 0x05, 0x70, 0x6f, 0x72, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x6f,
	0x72, 0x74, 0x52, 0x05, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x22, 0x1a, 0x0a, 0x06, 0x48, 0x61, 0x73,
	0x47, 0x55, 0x49, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x75, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x03, 0x67, 0x75, 0x69, 0x22, 0x0b, 0x0a, 0x09, 0x48, 0x61, 0x73, 0x47, 0x55, 0x49, 0x52,
	0x65, 0x71, 0x22, 0x12, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x65, 0x6e, 0x50, 0x6f,
	0x72, 0x74, 0x73, 0x52, 0x65, 0x71, 0x32, 0x84, 0x02, 0x0a, 0x08, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x12, 0x3d, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x15, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x22, 0x00, 0x12, 0x41, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e,
	0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x15, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x1a, 0x11, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x74, 0x6f,
	0x70, 0x70, 0x65, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x15, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x00, 0x12, 0x33, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x14, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x0d, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x00, 0x32, 0x49, 0x0a,
	0x08, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x12, 0x3d, 0x0a, 0x0f, 0x4c, 0x69, 0x73,
	0x74, 0x41, 0x6c, 0x6c, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x12, 0x15, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50,
	0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x22, 0x00, 0x32, 0x46, 0x0a, 0x0f, 0x48, 0x61, 0x72, 0x64,
	0x65, 0x6e, 0x69, 0x6e, 0x67, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x12, 0x33, 0x0a, 0x0d, 0x47,
	0x65, 0x74, 0x4c, 0x79, 0x6e, 0x69, 0x73, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x0e, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x4c, 0x79, 0x6e, 0x69, 0x73, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x00,
	0x32, 0x7a, 0x0a, 0x0b, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x39, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x65, 0x6e, 0x50, 0x6f, 0x72, 0x74, 0x73,
	0x12, 0x16, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x65, 0x6e,
	0x50, 0x6f, 0x72, 0x74, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x22, 0x00, 0x12, 0x30, 0x0a, 0x0d, 0x4d, 0x61,
	0x63, 0x68, 0x69, 0x6e, 0x65, 0x48, 0x61, 0x73, 0x47, 0x55, 0x49, 0x12, 0x0f, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x48, 0x61, 0x73, 0x47, 0x55, 0x49, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x48, 0x61, 0x73, 0x47, 0x55, 0x49, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_egida_proto_rawDescOnce sync.Once
	file_egida_proto_rawDescData = file_egida_proto_rawDesc
)

func file_egida_proto_rawDescGZIP() []byte {
	file_egida_proto_rawDescOnce.Do(func() {
		file_egida_proto_rawDescData = protoimpl.X.CompressGZIP(file_egida_proto_rawDescData)
	})
	return file_egida_proto_rawDescData
}

var file_egida_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_egida_proto_goTypes = []interface{}{
	(*Service)(nil),          // 0: grpc.Service
	(*ListService)(nil),      // 1: grpc.ListService
	(*ServiceNameReq)(nil),   // 2: grpc.ServiceNameReq
	(*ListServicesReq)(nil),  // 3: grpc.ListServicesReq
	(*Package)(nil),          // 4: grpc.Package
	(*ListPackage)(nil),      // 5: grpc.ListPackage
	(*ListPackagesReq)(nil),  // 6: grpc.ListPackagesReq
	(*LynisScore)(nil),       // 7: grpc.LynisScore
	(*ScoreReq)(nil),         // 8: grpc.ScoreReq
	(*Port)(nil),             // 9: grpc.Port
	(*ListPort)(nil),         // 10: grpc.ListPort
	(*HasGUI)(nil),           // 11: grpc.HasGUI
	(*HasGUIReq)(nil),        // 12: grpc.HasGUIReq
	(*ListOpenPortsReq)(nil), // 13: grpc.ListOpenPortsReq
}
var file_egida_proto_depIdxs = []int32{
	0,  // 0: grpc.ListService.services:type_name -> grpc.Service
	4,  // 1: grpc.ListPackage.packages:type_name -> grpc.Package
	9,  // 2: grpc.ListPort.ports:type_name -> grpc.Port
	3,  // 3: grpc.Services.ListAllServices:input_type -> grpc.ListServicesReq
	3,  // 4: grpc.Services.ListRunningServices:input_type -> grpc.ListServicesReq
	3,  // 5: grpc.Services.ListStoppedServices:input_type -> grpc.ListServicesReq
	2,  // 6: grpc.Services.GetService:input_type -> grpc.ServiceNameReq
	6,  // 7: grpc.Packages.ListAllPackages:input_type -> grpc.ListPackagesReq
	8,  // 8: grpc.HardeningScores.GetLynisScore:input_type -> grpc.ScoreReq
	13, // 9: grpc.MachineInfo.ListOpenPorts:input_type -> grpc.ListOpenPortsReq
	12, // 10: grpc.MachineInfo.MachineHasGUI:input_type -> grpc.HasGUIReq
	1,  // 11: grpc.Services.ListAllServices:output_type -> grpc.ListService
	1,  // 12: grpc.Services.ListRunningServices:output_type -> grpc.ListService
	1,  // 13: grpc.Services.ListStoppedServices:output_type -> grpc.ListService
	0,  // 14: grpc.Services.GetService:output_type -> grpc.Service
	5,  // 15: grpc.Packages.ListAllPackages:output_type -> grpc.ListPackage
	7,  // 16: grpc.HardeningScores.GetLynisScore:output_type -> grpc.LynisScore
	10, // 17: grpc.MachineInfo.ListOpenPorts:output_type -> grpc.ListPort
	11, // 18: grpc.MachineInfo.MachineHasGUI:output_type -> grpc.HasGUI
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_egida_proto_init() }
func file_egida_proto_init() {
	if File_egida_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_egida_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Service); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_egida_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListService); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_egida_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceNameReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_egida_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListServicesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_egida_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Package); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_egida_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPackage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_egida_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPackagesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_egida_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LynisScore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_egida_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScoreReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_egida_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Port); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_egida_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_egida_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HasGUI); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_egida_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HasGUIReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_egida_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListOpenPortsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_egida_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_egida_proto_goTypes,
		DependencyIndexes: file_egida_proto_depIdxs,
		MessageInfos:      file_egida_proto_msgTypes,
	}.Build()
	File_egida_proto = out.File
	file_egida_proto_rawDesc = nil
	file_egida_proto_goTypes = nil
	file_egida_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ServicesClient is the client API for Services service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServicesClient interface {
	ListAllServices(ctx context.Context, in *ListServicesReq, opts ...grpc.CallOption) (*ListService, error)
	ListRunningServices(ctx context.Context, in *ListServicesReq, opts ...grpc.CallOption) (*ListService, error)
	ListStoppedServices(ctx context.Context, in *ListServicesReq, opts ...grpc.CallOption) (*ListService, error)
	GetService(ctx context.Context, in *ServiceNameReq, opts ...grpc.CallOption) (*Service, error)
}

type servicesClient struct {
	cc grpc.ClientConnInterface
}

func NewServicesClient(cc grpc.ClientConnInterface) ServicesClient {
	return &servicesClient{cc}
}

func (c *servicesClient) ListAllServices(ctx context.Context, in *ListServicesReq, opts ...grpc.CallOption) (*ListService, error) {
	out := new(ListService)
	err := c.cc.Invoke(ctx, "/grpc.Services/ListAllServices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicesClient) ListRunningServices(ctx context.Context, in *ListServicesReq, opts ...grpc.CallOption) (*ListService, error) {
	out := new(ListService)
	err := c.cc.Invoke(ctx, "/grpc.Services/ListRunningServices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicesClient) ListStoppedServices(ctx context.Context, in *ListServicesReq, opts ...grpc.CallOption) (*ListService, error) {
	out := new(ListService)
	err := c.cc.Invoke(ctx, "/grpc.Services/ListStoppedServices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicesClient) GetService(ctx context.Context, in *ServiceNameReq, opts ...grpc.CallOption) (*Service, error) {
	out := new(Service)
	err := c.cc.Invoke(ctx, "/grpc.Services/GetService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServicesServer is the server API for Services service.
type ServicesServer interface {
	ListAllServices(context.Context, *ListServicesReq) (*ListService, error)
	ListRunningServices(context.Context, *ListServicesReq) (*ListService, error)
	ListStoppedServices(context.Context, *ListServicesReq) (*ListService, error)
	GetService(context.Context, *ServiceNameReq) (*Service, error)
}

// UnimplementedServicesServer can be embedded to have forward compatible implementations.
type UnimplementedServicesServer struct {
}

func (*UnimplementedServicesServer) ListAllServices(context.Context, *ListServicesReq) (*ListService, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAllServices not implemented")
}
func (*UnimplementedServicesServer) ListRunningServices(context.Context, *ListServicesReq) (*ListService, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRunningServices not implemented")
}
func (*UnimplementedServicesServer) ListStoppedServices(context.Context, *ListServicesReq) (*ListService, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListStoppedServices not implemented")
}
func (*UnimplementedServicesServer) GetService(context.Context, *ServiceNameReq) (*Service, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetService not implemented")
}

func RegisterServicesServer(s *grpc.Server, srv ServicesServer) {
	s.RegisterService(&_Services_serviceDesc, srv)
}

func _Services_ListAllServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServicesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicesServer).ListAllServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Services/ListAllServices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicesServer).ListAllServices(ctx, req.(*ListServicesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Services_ListRunningServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServicesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicesServer).ListRunningServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Services/ListRunningServices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicesServer).ListRunningServices(ctx, req.(*ListServicesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Services_ListStoppedServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServicesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicesServer).ListStoppedServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Services/ListStoppedServices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicesServer).ListStoppedServices(ctx, req.(*ListServicesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Services_GetService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceNameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicesServer).GetService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Services/GetService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicesServer).GetService(ctx, req.(*ServiceNameReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Services_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Services",
	HandlerType: (*ServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAllServices",
			Handler:    _Services_ListAllServices_Handler,
		},
		{
			MethodName: "ListRunningServices",
			Handler:    _Services_ListRunningServices_Handler,
		},
		{
			MethodName: "ListStoppedServices",
			Handler:    _Services_ListStoppedServices_Handler,
		},
		{
			MethodName: "GetService",
			Handler:    _Services_GetService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "egida.proto",
}

// PackagesClient is the client API for Packages service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PackagesClient interface {
	ListAllPackages(ctx context.Context, in *ListPackagesReq, opts ...grpc.CallOption) (*ListPackage, error)
}

type packagesClient struct {
	cc grpc.ClientConnInterface
}

func NewPackagesClient(cc grpc.ClientConnInterface) PackagesClient {
	return &packagesClient{cc}
}

func (c *packagesClient) ListAllPackages(ctx context.Context, in *ListPackagesReq, opts ...grpc.CallOption) (*ListPackage, error) {
	out := new(ListPackage)
	err := c.cc.Invoke(ctx, "/grpc.Packages/ListAllPackages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PackagesServer is the server API for Packages service.
type PackagesServer interface {
	ListAllPackages(context.Context, *ListPackagesReq) (*ListPackage, error)
}

// UnimplementedPackagesServer can be embedded to have forward compatible implementations.
type UnimplementedPackagesServer struct {
}

func (*UnimplementedPackagesServer) ListAllPackages(context.Context, *ListPackagesReq) (*ListPackage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAllPackages not implemented")
}

func RegisterPackagesServer(s *grpc.Server, srv PackagesServer) {
	s.RegisterService(&_Packages_serviceDesc, srv)
}

func _Packages_ListAllPackages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPackagesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackagesServer).ListAllPackages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Packages/ListAllPackages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackagesServer).ListAllPackages(ctx, req.(*ListPackagesReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Packages_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Packages",
	HandlerType: (*PackagesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAllPackages",
			Handler:    _Packages_ListAllPackages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "egida.proto",
}

// HardeningScoresClient is the client API for HardeningScores service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HardeningScoresClient interface {
	GetLynisScore(ctx context.Context, in *ScoreReq, opts ...grpc.CallOption) (*LynisScore, error)
}

type hardeningScoresClient struct {
	cc grpc.ClientConnInterface
}

func NewHardeningScoresClient(cc grpc.ClientConnInterface) HardeningScoresClient {
	return &hardeningScoresClient{cc}
}

func (c *hardeningScoresClient) GetLynisScore(ctx context.Context, in *ScoreReq, opts ...grpc.CallOption) (*LynisScore, error) {
	out := new(LynisScore)
	err := c.cc.Invoke(ctx, "/grpc.HardeningScores/GetLynisScore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HardeningScoresServer is the server API for HardeningScores service.
type HardeningScoresServer interface {
	GetLynisScore(context.Context, *ScoreReq) (*LynisScore, error)
}

// UnimplementedHardeningScoresServer can be embedded to have forward compatible implementations.
type UnimplementedHardeningScoresServer struct {
}

func (*UnimplementedHardeningScoresServer) GetLynisScore(context.Context, *ScoreReq) (*LynisScore, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLynisScore not implemented")
}

func RegisterHardeningScoresServer(s *grpc.Server, srv HardeningScoresServer) {
	s.RegisterService(&_HardeningScores_serviceDesc, srv)
}

func _HardeningScores_GetLynisScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScoreReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HardeningScoresServer).GetLynisScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.HardeningScores/GetLynisScore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HardeningScoresServer).GetLynisScore(ctx, req.(*ScoreReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _HardeningScores_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.HardeningScores",
	HandlerType: (*HardeningScoresServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLynisScore",
			Handler:    _HardeningScores_GetLynisScore_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "egida.proto",
}

// MachineInfoClient is the client API for MachineInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MachineInfoClient interface {
	ListOpenPorts(ctx context.Context, in *ListOpenPortsReq, opts ...grpc.CallOption) (*ListPort, error)
	MachineHasGUI(ctx context.Context, in *HasGUIReq, opts ...grpc.CallOption) (*HasGUI, error)
}

type machineInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewMachineInfoClient(cc grpc.ClientConnInterface) MachineInfoClient {
	return &machineInfoClient{cc}
}

func (c *machineInfoClient) ListOpenPorts(ctx context.Context, in *ListOpenPortsReq, opts ...grpc.CallOption) (*ListPort, error) {
	out := new(ListPort)
	err := c.cc.Invoke(ctx, "/grpc.MachineInfo/ListOpenPorts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineInfoClient) MachineHasGUI(ctx context.Context, in *HasGUIReq, opts ...grpc.CallOption) (*HasGUI, error) {
	out := new(HasGUI)
	err := c.cc.Invoke(ctx, "/grpc.MachineInfo/MachineHasGUI", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MachineInfoServer is the server API for MachineInfo service.
type MachineInfoServer interface {
	ListOpenPorts(context.Context, *ListOpenPortsReq) (*ListPort, error)
	MachineHasGUI(context.Context, *HasGUIReq) (*HasGUI, error)
}

// UnimplementedMachineInfoServer can be embedded to have forward compatible implementations.
type UnimplementedMachineInfoServer struct {
}

func (*UnimplementedMachineInfoServer) ListOpenPorts(context.Context, *ListOpenPortsReq) (*ListPort, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOpenPorts not implemented")
}
func (*UnimplementedMachineInfoServer) MachineHasGUI(context.Context, *HasGUIReq) (*HasGUI, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MachineHasGUI not implemented")
}

func RegisterMachineInfoServer(s *grpc.Server, srv MachineInfoServer) {
	s.RegisterService(&_MachineInfo_serviceDesc, srv)
}

func _MachineInfo_ListOpenPorts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOpenPortsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineInfoServer).ListOpenPorts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.MachineInfo/ListOpenPorts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineInfoServer).ListOpenPorts(ctx, req.(*ListOpenPortsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineInfo_MachineHasGUI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HasGUIReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineInfoServer).MachineHasGUI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.MachineInfo/MachineHasGUI",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineInfoServer).MachineHasGUI(ctx, req.(*HasGUIReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _MachineInfo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.MachineInfo",
	HandlerType: (*MachineInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListOpenPorts",
			Handler:    _MachineInfo_ListOpenPorts_Handler,
		},
		{
			MethodName: "MachineHasGUI",
			Handler:    _MachineInfo_MachineHasGUI_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "egida.proto",
}
